import '@/styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Catatan',
  description: 'Generated by my catatan app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='max-w-2xl m-auto my-8'>{children}</main>
      </body>
    </html>
  )
}
